import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Footer, Header, Sidebar } from "@/components";
import { Suspense } from "react";

const montserrat = localFont({
  src: './fonts/Montserrat.ttf',
  variable: "--font-montserrat-sans",
  weight: '100 900'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>

        <Suspense fallback={<div>Loading...</div>}>
          <Header />

          {children}

          <Footer />
        </Suspense>

      </body>
    </html>
  );
}

