import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Footer, Header } from "@/components";

const montserrat = localFont({
  src: './fonts/Montserrat.ttf',
  variable: "--font-montserrat-sans",
  weight: '100 900'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>

        <Header />

        {children}

        <Footer />

      </body>
    </html>
  );
}

